version: '2'
services:
  zookeeper:
    image: debezium/zookeeper:1.3
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
  kafka-1:
    image: debezium/kafka:1.3
    ports:
      - 9092:9092
    links:
      - zookeeper
    environment:
      - BROKER_ID=1
      - ZOOKEEPER_CONNECT=zookeeper:2181
  kafka-2:
    image: debezium/kafka:1.3
    ports:
      - 9093:9092
    links:
      - zookeeper
    environment:
      - BROKER_ID=2
      - ZOOKEEPER_CONNECT=zookeeper:2181
  postgres:
    image: debezium/postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  connect:
    image: debezium/connect:1.3
    ports:
      - 8083:8083
    links:
      - kafka-1
      - postgres
    environment:
      - BOOTSTRAP_SERVERS=kafka-1:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_connect_statuses
